# Generated by Django 4.1.7 on 2023-03-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cat_kinds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catkinds',
            options={'ordering': ['likes', 'british'], 'verbose_name': 'Cat kinds', 'verbose_name_plural': 'Cat kinds'},
        ),
    ]
